name: stagexl_samples
author: Bernhard Pichler
description: Sample applications showing features of the StageXL library.
homepage: http://www.stagexl.org/
dependencies:
  browser: any
  stagexl: any
  stagexl_bitmapfont: any
  stagexl_flump: any
  stagexl_richtextfield: any
  stagexl_spine: any
  stagexl_gaf: any
transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
